services:
  db:
    container_name: '${APP_NAME}-db'
    image: postgres
    volumes:
      - storage_db:/var/lib/postgres/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - adonis-net
  app:
    build: .
    container_name: '${APP_NAME}-api'
    ports:
      - "3333:3333"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - adonis-net


volumes:
  storage_db:
  
networks:
  adonis-net:
    driver: bridge
